FROM python:3.13-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pyproject.toml ./

RUN pip install --upgrade pip
RUN pip install .

COPY app ./app
COPY gRPC ./gRPC

EXPOSE 50051

CMD ["python", "-m", "gRPC.src.server"]