# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gRPC.src.users_service_pb2 as users__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in users_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Сервис для работы с сервисом пользователей
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserByEmail = channel.unary_unary(
                '/users.v1.UserService/GetUserByEmail',
                request_serializer=users__service__pb2.GetUserByEmailRequest.SerializeToString,
                response_deserializer=users__service__pb2.GetUserByEmailResponse.FromString,
                _registered_method=True)
        self.CreateUserByEmail = channel.unary_unary(
                '/users.v1.UserService/CreateUserByEmail',
                request_serializer=users__service__pb2.GetUserByEmailRequest.SerializeToString,
                response_deserializer=users__service__pb2.GetUserByEmailResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Сервис для работы с сервисом пользователей
    """

    def GetUserByEmail(self, request, context):
        """Возвращает информацию о пользователе по id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUserByEmail(self, request, context):
        """Создаeт пользователя с заданным email
        (временно: до реализации notifications задает is_verified = true )
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByEmail,
                    request_deserializer=users__service__pb2.GetUserByEmailRequest.FromString,
                    response_serializer=users__service__pb2.GetUserByEmailResponse.SerializeToString,
            ),
            'CreateUserByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserByEmail,
                    request_deserializer=users__service__pb2.GetUserByEmailRequest.FromString,
                    response_serializer=users__service__pb2.GetUserByEmailResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'users.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('users.v1.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Сервис для работы с сервисом пользователей
    """

    @staticmethod
    def GetUserByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users.v1.UserService/GetUserByEmail',
            users__service__pb2.GetUserByEmailRequest.SerializeToString,
            users__service__pb2.GetUserByEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUserByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users.v1.UserService/CreateUserByEmail',
            users__service__pb2.GetUserByEmailRequest.SerializeToString,
            users__service__pb2.GetUserByEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
