syntax = "proto3";

package users.v1;

// Сервис для работы с сервисом пользователей
service UserService {
    // Возвращает информацию о пользователе по email
    rpc GetUserByEmail (GetUserByEmailRequest) returns (GetUserByEmailResponse);

    // Возвращает информацию о пользователе по id
    rpc GetUserByID (GetUserByIdRequest) returns (GetUserByIdResponse);

    // Создаeт пользователя с заданным email
    // (временно: до реализации notifications задает is_verified = true )
    rpc CreateUserByEmail (GetUserByEmailRequest) returns (GetUserByEmailResponse);

    rpc VerifiedUserById (VerifyUserByIdRequest) returns (GetUserByEmailResponse);
}

// Сообщение запроса, содержит email
message GetUserByEmailRequest {
    string email = 1;
}

// Сообщение ответ, содержит id, is_active, is_verified
message GetUserByEmailResponse {
    string id = 1;          // UUID v4
    bool is_active = 2;
    bool is_verified = 3;
}

message VerifyUserByIdRequest {
    string id = 1;
}

message GetUserByIdRequest {
    string id = 1;
}

message GetUserByIdResponse {
    string id = 1;
    string email = 2;
    bool is_active = 3;
    bool is_verified = 4;
}